### ISSUE TITLE
Reproduce Results

### ISSUE THREAD

**Issue by Wienhannover** [jsyoon0823/INVASE#3]
Hello,

I used the recommended hyperparameters from the other issue, but ran into NaNs problems, which means the produced selection_probability after several iterations contained NaNs, and the program stopped.

Hyperparameters used:
Syn4: activation = selu, lamda = 0.1 (Smaller TPR but still the best model)
Syn5: activation = selu, lamda = 0.15
Syn6: activation = selu, lamda = 0.1

Does the activation function "selu" really make a big difference, compared with "relu"? Is there any reason for using "selu" specificly?

Thanks for help in advance!

**Comment by jsyoon0823** [comment]
Actually, selu makes a big difference in Syn3, Syn4, Syn5, and Syn6.
- This is also true in the other paper (with the same synthetic data) - https://github.com/Jianbo-Lab/L2X
Unfortunately, I did not meet NaN issues for selu (with tensorflow 1.15).
Also, I got the same results with the recommended hyper-parameters. Please use main_invase file instead of notebook files.
